# Site settings
title: Vancouver Resistance
email: vanre.org
url: http://vanre.org
description: "Defending Vancouver from the Shaper Ingression"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Niantic Labs and VanRE

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus
    url: https://plus.google.com/u/0/communities/110103291757340972073
  - title: facebook
    url: https://www.facebook.com/pages/Vancouver-Ingress-Resistance/301839143324437

# Build settings
markdown: kramdown
permalink: pretty
